### ISSUE TITLE
Change Names of fontSize in tailwind.config.js

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/ramsay-site#2]
https://www.loom.com/share/8c1095b864b34e04b4ad91203b03cab7

**Comment by kirti75waytech** [comment]
This is done today, please verify and let me know if any other change required.

**Comment by thecodeclimber** [comment]
Thanks -- but I'd still like to make one more change.

This is the current code: 

```
fontSize: {
        "font-xs": "0.625rem",
        "font-sm": "1.063rem",
        "font-md": "1.125rem",
        "font-lg": "3.125rem",
      },
```

Please change to this:

```
fontSize: {
        "xs": "0.625rem",
        "sm": "1.063rem",
        "md": "1.125rem",
        "lg": "3.125rem",
      },
```

Thanks.

**Comment by lokesh75way** [comment]
@thecodeclimber how can I change it to 
{
        "xs": "0.625rem",
        "sm": "1.063rem",
        "md": "1.125rem",
        "lg": "3.125rem",
}
because these classes "xs", "sm" etc are already defined in tailwind and these are already getting used somewhere else on the page. So if I use the same name then it will overwrite the previous one which we don't want because as per the design we need both the sizes. For ex : "xs": "0.75rem", and "font-xs": "0.625rem". So that's why I have added prefix "font-" to make it distinguish class.

Please advise your thoughts on this?

Thanks

**Comment by kirti75waytech** [comment]
@thecodeclimber same here, added comments mistakenly from Lokesh's github account. So please ignore account issue. and just follow the comments.

**Comment by thecodeclimber** [comment]
Good question.  It requires some explanation -- which I did in a video.  It's a bit long (8 minutes), but I think it's important to watch and understand.  After you watch it, please let me know if you have any thoughts or questions.  

Here it is:  https://www.loom.com/share/b0728a604fbf40b8a82cdd61d62ada0b

**Comment by kirti75waytech** [comment]
@thecodeclimber Thanks for the explanation through video.

Although here are the reason why I did that way just for your reference:

Regarding Design Changes :
I have noticed that the designs have been changed now on FIGMA because of which the font's now looks consistent where as previous they were not consistent. This is the reason why I took custom fonts in config file.

For example : 

- Design changes on below section on FIGMA:
    Our Founder Section:	
        Earlier: text was not bold
	Now: It is bold 
The Ramsay Commitment Section: 
    Ealier: Blurb font size 17px   	 
    Now: It is 20px, Font size 17px still exist on tablet view 

Testimonials Section: 
    Earlier: blurb was not bold 
    Now: It is bold and so on...

But now I am changing the code as per you suggested in video and following the latest design over figma.
Thanks

**Comment by thecodeclimber** [comment]
Got it -- thanks for clarifying :)

**Comment by kirti75waytech** [comment]
@thecodeclimber Completed and deployed. Please verify and let me know if you need any other change. Thanks

**Comment by thecodeclimber** [comment]
Thanks -- much appreciated.
