### ISSUE TITLE
Remove Isomorphic Image on Tablet & Mobile

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/ramsay-site#27]
Please remove the Isomorphic Image on both Tablet & Mobile view. 

I am referring to this image:

![image](https://user-images.githubusercontent.com/65869221/100918293-f99bfb80-34e0-11eb-8d0d-f9816af16af1.png)

**Comment by kirti75waytech** [comment]
@thecodeclimber Today I have fixed the display issue with this image on the tablet and mobile view and it looks much better and as expected. So In think we can keep it now instead of removing it. Please let me know if you still wants to remove it? Or else you can close the ticket. 

See attached screenshot from mobile view :
![File](https://user-images.githubusercontent.com/74037279/101022417-62de4600-3597-11eb-9c8e-ec041087f4e9.jpg)

**Comment by thecodeclimber** [comment]
we'll keep this also -- thanks. 👍
