### ISSUE TITLE
Remove Bio Photo On Tablet & Mobile

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/ramsay-site#29]
Please remove the bio photo on tablet and mobile view.

I am referring to this image:

![image](https://user-images.githubusercontent.com/65869221/100923186-7f22aa00-34e7-11eb-8e0e-d3e826370e93.png)

**Comment by kirti75waytech** [comment]
@thecodeclimber Today I have fixed the display issue with this image on the tablet and mobile view and it looks much better and as expected. So In think we can keep it now instead of removing it. Please let me know if you still wants to remove it? Or else you can close the ticket. 

See attached screenshot from mobile view :
![File (1)](https://user-images.githubusercontent.com/74037279/101022618-a20c9700-3597-11eb-83f0-0f0e24b65cf9.jpg)

**Comment by thecodeclimber** [comment]
Let's keep it -- thanks.
